const notes = [
  // Lower octave keys (C3 to B3)
  { name: "C3", key: "q", octave: 3 },
  { name: "C#3", key: "w", octave: 3 },
  { name: "D3", key: "e", octave: 3 },
  { name: "D#3", key: "r", octave: 3 },
  { name: "E3", key: "t", octave: 3 },
  { name: "F3", key: "y", octave: 3 },
  { name: "F#3", key: "u", octave: 3 },
  { name: "G3", key: "i", octave: 3 },
  { name: "G#3", key: "o", octave: 3 },
  { name: "A3", key: "p", octave: 3 },
  { name: "A#3", key: "[", octave: 3 },
  { name: "B3", key: "]", octave: 3 },

  // Middle octave keys (C4 to B4)
  { name: "C4", key: "a", octave: 4 },
  { name: "C#4", key: "s", octave: 4 },
  { name: "D4", key: "d", octave: 4 },
  { name: "D#4", key: "f", octave: 4 },
  { name: "E4", key: "g", octave: 4 },
  { name: "F4", key: "h", octave: 4 },
  { name: "F#4", key: "j", octave: 4 },
  { name: "G4", key: "k", octave: 4 },
  { name: "G#4", key: "l", octave: 4 },
  { name: "A4", key: ";", octave: 4 },
  { name: "A#4", key: "'", octave: 4 },
  { name: "B4", key: '"', octave: 4 },

  // Upper octave keys (C5 to B5)
  { name: "C5", key: "z", octave: 5 },
  { name: "C#5", key: "x", octave: 5 },
  { name: "D5", key: "c", octave: 5 },
  { name: "D#5", key: "v", octave: 5 },
  { name: "E5", key: "b", octave: 5 },
  { name: "F5", key: "n", octave: 5 },
  { name: "F#5", key: "m", octave: 5 },
  { name: "G5", key: ",", octave: 5 },
  { name: "G#5", key: ".", octave: 5 },
  { name: "A5", key: "/", octave: 5 },
  { name: "A#5", key: "1", octave: 5 },
  { name: "B5", key: "2", octave: 5 },

  // Highest octave keys (C6 to B6)
  { name: "C6", key: "3", octave: 6 },
  { name: "C#6", key: "4", octave: 6 },
  { name: "D6", key: "5", octave: 6 },
  { name: "D#6", key: "6", octave: 6 },
  { name: "E6", key: "7", octave: 6 },
  { name: "F6", key: "8", octave: 6 },
  { name: "F#6", key: "9", octave: 6 },
  { name: "G6", key: "0", octave: 6 },
  { name: "G#6", key: "-", octave: 6 },
  { name: "A6", key: "=", octave: 6 },
  { name: "A#6", key: "_", octave: 6 },
  { name: "B6", key: "{", octave: 6 },

  // Additional highest keys to complete the 61-note range
  { name: "C7", key: "}", octave: 7 },
  { name: "C#7", key: "&", octave: 7 },
  { name: "D7", key: "*", octave: 7 },
  { name: "D#7", key: "(", octave: 7 },
  { name: "E7", key: ")", octave: 7 },
  { name: "F7", key: "^", octave: 7 },
  { name: "F#7", key: "#", octave: 7 },
  { name: "G7", key: "$", octave: 7 },
  { name: "G#7", key: "@", octave: 7 },
  { name: "A7", key: "!", octave: 7 },
  { name: "A#7", key: "?", octave: 7 },
  { name: "B7", key: "%", octave: 7 },
  { name: "B7", key: "+", octave: 7 },
];

export const urls = {
  A0: "A0.mp3",
  C1: "C1.mp3",
  "D#1": "Ds1.mp3",
  "F#1": "Fs1.mp3",
  A1: "A1.mp3",
  C2: "C2.mp3",
  "D#2": "Ds2.mp3",
  "F#2": "Fs2.mp3",
  A2: "A2.mp3",
  C3: "C3.mp3",
  "D#3": "Ds3.mp3",
  "F#3": "Fs3.mp3",
  A3: "A3.mp3",
  C4: "C4.mp3",
  "D#4": "Ds4.mp3",
  "F#4": "Fs4.mp3",
  A4: "A4.mp3",
  C5: "C5.mp3",
  "D#5": "Ds5.mp3",
  "F#5": "Fs5.mp3",
  A5: "A5.mp3",
  C6: "C6.mp3",
  "D#6": "Ds6.mp3",
  "F#6": "Fs6.mp3",
  A6: "A6.mp3",
  C7: "C7.mp3",
};

export default notes;
